### ISSUE TITLE
Update snRNA-seq and scRNA-seq alt names

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#85] opened 2023-11-02 15:51 UTC
For `snRNA-seq` we want to add `snRNAseq` as an alt name.

For `scRNA-seq` we want to add `scRNAseq` as an alt name.

This is to support the Ingest Validation Tools with the latest CEDAR updates.
@bhonick for reference

**Comment by maxsibilla** [comment] 2023-11-02 19:34
The primary issue is that when submitting a dataset for pipeline processing the metadata.tsv file requires a field for `assay_type`. When `scRNAseq` is specified, which is a supported datatype as per the Ingest Validation Tools, a POST is made to https://search-api.dev.sennetconsortium.org/assayname with the request body of:
```
{
    "name": "scRNAseq"
}
```
This endpoint returns all attributes found in the UBKG `/datasets` endpoint for the provided assay type (including alt-names). **The UBKG supports "scRNA-seq" but not "scRNAseq".** 

After discussing with @shirey and @bhonick more information needs to be gathered before making any decisions. Currently we trying to verify what `scRNAseq` and `snRNAseq` equate to (e.g. does `snRNAseq` equal `snRNA-seq (10x Genomics v3)`) from the CEDAR spec (https://bioportal.bioontology.org/ontologies/HRAVS/?p=classes&conceptid=https%3A%2F%2Fpurl.humanatlas.io%2Fvocab%2Fhravs%23HRAVS_0000248).

Another point that emerged from this discussion is the potential that `snRNA-seq` and `snRNA-seq (10x Genomics v3)` may equate to the same thing and could be redundant. 
<img width="412" alt="image" src="https://github.com/x-atlas-consortia/ubkg-api/assets/7218802/311d044f-e6d9-4336-8466-ed852709752c">

One potential resolution for this may be to alter the existing data types of `scRNA-seq` and `snRNA-seq` and then updating the Neo4j databases to modify the existing datasets to match the updated spec.

**Comment by maxsibilla** [comment] 2023-11-10 19:04
@AlanSimmons I believe we want to replace the existing `scRNA-seq` with this one from HuBMAP
<img width="421" alt="image" src="https://github.com/x-atlas-consortia/ubkg-api/assets/7218802/d0af5be5-b669-47e7-adbd-fb4109364c45">

@shirey does that seem right?

**Comment by maxsibilla** [comment] 2023-11-10 19:17
Additionally we will also want to bring over the "scRNAseq-10xGenomics-v2" assay type
<img width="417" alt="image" src="https://github.com/x-atlas-consortia/ubkg-api/assets/7218802/48990e82-18f2-4877-8cab-61a06137bc83">

**Comment by AlanSimmons** [comment] 2023-11-10 19:35
There was some confusion over this that has only now been resolved.

`scRNA-seq` is not really a v1 data_type. It is not in the SenNet [workflows](https://github.com/sennetconsortium/ingest-pipeline/blob/devel/src/ingest-pipeline/airflow/dags/workflow_map.yml), for example.

It's more like one of the new "Dataset Data Types"--i.e., a category. 

I recommend that we synchronize data_types between HuBMAP and SenNet, at least for the data types and pipelines that are common to both applications.

**Comment by shirey** [comment] 2023-11-10 19:40
@AlanSimmons There has been A LOT of recent back and forth on this the result of which confirms that doing what Max is asking here will actually put us in line with getting the correct pipelines aligned with the correct data in SenNet.

**Comment by shirey** [comment] 2023-11-10 19:41
@AlanSimmons and @maxsibilla when this has been released the database `Dataset.data_types` fields will need to be updated on the affected datasests.

**Comment by AlanSimmons** [comment] 2023-11-10 20:09
I identify at least 7 requests in one card. I'm not sure whether some of the things are actual requests or proposed requests.

Please confirm that this is the request:
1. For existing data_type `snRNA-seq`, add the alt-name `snRNAseq`.
2. For existing data_type `scRNA-seq`, add the alt-name `scRNAseq'.
3. Delete the existing snRNA-seq, as it is a duplicate of snRNA-seq (10x Genomics v3).
4. Synchronize the existing`snRNA-seq (10x Genomics v3)` in the SENNET ontology with the HUBMAP ontology.
5. Delete the existing scRNA-seq. 
6. Copy over the scRNASeq-10xgenomics dataset from HUBMAP.
7. Copy over the scRNASeq-10xgenomics-v2 dataset from HUBMAP.

But wait--you asked both to add an alt-name to scRNA-seq and also to delete it. Do you mean to add an alt-name to the scRNASeq-10xgenomics dataset that we're copying over from HUBMAP? Should we also add the alt-name to the scRNASeq-10xgenomics-v2 dataset that we're copying over from HUBMAP? Why don't the HUBMAP versions already have the alt-name, if we're just porting things over?

**Comment by shirey** [comment] 2023-11-10 20:13
@AlanSimmons After much discussion (only a bit of it documented here) the last two comments from Max are what we need.  @maxsibilla if it helps, maybe close this card and create a new one.

**Comment by maxsibilla** [comment] 2023-11-10 20:13
@AlanSimmons I wasn't sure whether to just close this card and create a new one or just update this one.

The ask is to:
1. Remove the existing `scRNA-seq` assay type
2. Copy over the `scRNAseq-10xGenomics-v3` dataset from HUBMAP.
3. Copy over the `scRNAseq-10xGenomics-v2` dataset from HUBMAP

**Comment by AlanSimmons** [comment] 2023-11-13 18:12
# Changes to SENNET source:
1. Removed scRNA-seq and its associated nodes.
2. Copied over scRNASeq-10xGenomics-v3 assay and associated nodes.
3. Copied over scRNASeq-10xGenomics-v2 assay and associated nodes.
4. Changed `derived_from` relationship from scRNA-seq (10x Genomics) [Salmon] dataset from scRNA-seq to above 2 assays. (This is currently transparent, but was in the ontology.)

**Comment by AlanSimmons** [comment] 2023-11-13 18:53
in Globus

**Closed** 2024-03-26 16:33 UTC
Labels: enhancement, SenNet, HuBMAP/SenNet
