### ISSUE TITLE
SenNet Incorrect Entity Type returned

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-api#22] opened 2023-04-11 16:00 UTC
https://ontology.api.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C000012&child_sabs=SENNET

"Sample Type" is returned when it should just be "Sample"

**Comment by AlanSimmons** [comment] 2023-04-12 18:33
Duplicate of #23

**Closed** 2023-04-12 18:33 UTC
Labels: bug, SenNet
